In [ ]:
#Minesweeper board


**This project i make for sharpen my nkowledge and skills in numpy **

In [1]:
import numpy as np

# Initialize a 5x5 board: 0 = empty, 1 = mine
board = np.zeros((5, 5), dtype=int)

# Randomly place 5 mines
mines = np.random.choice(25, 5, replace=False)
board[np.unravel_index(mines, board.shape)] = 1

print("Minesweeper Board (1 = mine, 0 = empty):\n", board)

# Create a board to store the mine counts
counts = np.zeros((5, 5), dtype=int)

# Directions for 8 neighbors
dirs = [(-1, -1), (-1, 0), (-1, 1),
        (0, -1),          (0, 1),
        (1, -1),  (1, 0), (1, 1)]

# Calculate neighboring mine counts
for row in range(5):
    for col in range(5):
        if board[row, col] == 1:
            counts[row, col] = -1  # Mark mines with -1
        else:
            count = 0
            for dr, dc in dirs:
                r, c = row + dr, col + dc
                if 0 <= r < 5 and 0 <= c < 5 and board[r, c] == 1:
                    count += 1
            counts[row, col] = count

print("\nBoard with mine counts (-1 means mine):\n", counts)

# Pretty print the board
print("\nPretty Minesweeper Board:")
for row in counts:
    row_display = ""
    for cell in row:
        if cell == -1:
            row_display += " * "
        else:
            row_display += f" {cell} "
    print(row_display)

# Optional: Reveal a specific cell (row, col)
reveal_row, reveal_col = 2, 2
print(f"\nReveal cell ({reveal_row}, {reveal_col}):")
if counts[reveal_row, reveal_col] == -1:
    print("💥 BOOM! It's a mine!")
else:
    print(f"Safe! {counts[reveal_row, reveal_col]} neighboring mines.")


Minesweeper Board (1 = mine, 0 = empty):
 [[1 0 1 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]]

Board with mine counts (-1 means mine):
 [[-1  3 -1  2  0]
 [ 2  4 -1  2  0]
 [ 2 -1  3  1  0]
 [ 2 -1  2  0  0]
 [ 1  1  1  0  0]]

Pretty Minesweeper Board:
 *  3  *  2  0 
 2  4  *  2  0 
 2  *  3  1  0 
 2  *  2  0  0 
 1  1  1  0  0 

Reveal cell (2, 2):
Safe! 3 neighboring mines.
