In [ ]:
# matrix calculation using numpy


In [1]:
import numpy as np

# Define two random matrices
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Addition
print("A + B:\n", A + B)

# Multiplication
print("A * B:\n", np.dot(A, B))

# Determinant
print("Determinant of A:", np.linalg.det(A))

# Inverse
if np.linalg.det(A) != 0:
    print("Inverse of A:\n", np.linalg.inv(A))
else:
    print("A is singular.")


Matrix A:
 [[2 1 1]
 [4 2 2]
 [8 5 3]]
Matrix B:
 [[9 1 3]
 [2 1 8]
 [3 7 3]]
A + B:
 [[11  2  4]
 [ 6  3 10]
 [11 12  6]]
A * B:
 [[23 10 17]
 [46 20 34]
 [91 34 73]]
Determinant of A: 0.0
A is singular.


In [2]:
# Transpose
print("\nTranspose of A:\n", A.T)

# Determinant
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

# Rank
print("\nRank of A:", np.linalg.matrix_rank(A))

# Trace
print("\nTrace of A:", np.trace(A))


Transpose of A:
 [[2 4 8]
 [1 2 5]
 [1 2 3]]

Determinant of A: 0.0

Rank of A: 2

Trace of A: 7
